language: csharp
sudo: required
dist: trusty
addons:
  chrome: stable

before_install:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: latest
dotnet: 2.1.4
os:
  - linux

script:
  - ./build.sh
