image: Visual Studio 2015

environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version

build_script:
  - ps: .\build.ps1 -Target OpenCover

after_build:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh